leveling:
    power: 1.5
    maxExperience: 90000
    maxLevel: 20
    classSwitchLevel: 20
    expLoss: 0.05
    max-tracked-blocks: 1000
    block-tracking-duration: 600000
    resetExpOnClassChange: false
properties:
    iConomy: false
    swapCost: 10
    prefix: 'Heroes:'
    color: 'RED'